use_frameworks!

platform :ios, '8.0'

target 'XCCommonTools_Example' do
  pod 'XCCommonTools', :path => '../'

  target 'XCCommonTools_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
